<a href="https://colab.research.google.com/github/aaaanwz/aaaanwz/blob/main/twitter%E6%84%9F%E6%83%85%E5%88%86%E6%9E%90.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvcc -V
!nvidia-smi

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
Tue Jun 21 12:38:36 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.46       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   71C    P8    11W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

テストデータ用意

In [2]:
!pip install neologdn demoji

Requirement already satisfied: neologdn in /usr/local/lib/python3.7/dist-packages (0.5.1)
Requirement already satisfied: demoji in /usr/local/lib/python3.7/dist-packages (1.1.0)

In [3]:
import pandas as pd
import neologdn
import demoji

FILENAME='data.csv'
train = pd.read_csv(FILENAME).query('labels == labels')
test = pd.read_csv(FILENAME).query('labels != labels').drop('labels',axis=1)

import re

def trim(text):
    text = neologdn.normalize(text)
    text=re.sub(r'[#＃@＃]\w+',"",text) #remove hashtag and mension
    text=re.sub(r'(https?|http)(:\/\/[-_\.!~*\'()a-zA-Z0-9;\/?:\@&=\+\$,%#]+)', "" ,text) #remove url
    text=re.sub(r'[\(\)【].+?[】\{\}]',"",text)
    text=demoji.replace(string=text, repl="")
    text=re.sub("[�▼]","",text)
    return text

train['text'] = train['text'].map(trim)
train['labels'] = train['labels'].astype(int)
test['text'] = test['text'].map(trim)
train.head(100)

                                                 text  labels
0      退職代行を利用するのはあり?なし?利用する際の注意点も解説!\n\n\n\n\n\n\n\n       1
1   よいしょYoutubeう!\nJava Ⅱ学習編:15ラストやっちゃう?総合課題\n\n\n...       3
2   \n記事タイトル:R言語でパッケージのロードに失敗した際の解決手順\n\n 詳しくはこちら\...       1
3   データミックスの評判・口コミは?講師はガチなデータサイエンティスト?\n\n\n\n\n\n...       1
4   Code Village(コードビレッジ)の評判・口コミが凄い?\n\n\n\n\n\n\n...       1
..                                                ...     ...
95  「JavaScript」\nで人気があるツイートです!(最新50件中)\n\n[いいね:7]...       2
96  \nまずはProgateで最初期の入門を乗り越えましょう!\nそのあとの理解を深めるためには...       3
97  \n記事タイトル:PythonでXPathを使ってスクレイピングする手順\n\n 詳しくはこ...       1
98  \n記事タイトル:PostgreSQL14を5手順でインストールする方法\n\n 詳しくはこ...       1
99  オンラインプログラミング学習サービス「Progate」を国際教養学科グローバルスタディーズ専...       3

[100 rows x 2 columns]

分類

In [4]:
!pip install simpletransformers pyarrow>=6.0.0 fugashi ipadic

In [5]:
from simpletransformers.classification import ClassificationArgs, ClassificationModel
import torch
import logging

logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

args = ClassificationArgs(num_train_epochs=1, overwrite_output_dir=True)
model = ClassificationModel("bert", "cl-tohoku/bert-base-japanese-whole-word-masking", num_labels=4, args=args, use_cuda=torch.cuda.is_available())

Some weights of the model checkpoint at cl-tohoku/bert-base-japanese-whole-word-masking were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-whole-word-masking and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'BertJapaneseTokenizer'.
The class this function is called from is 'BertTokenizer'.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'BertJapaneseTokenizer'.
The class this function is called from is 'BertTokenizerFast'.

In [6]:
# Train the model
model.train_model(train)
# Evaluate the model
result, model_outputs, wrong_predictions = model.eval_model(train)

INFO:simpletransformers.classification.classification_utils: Converting to features started. Cache is not used.

  0%|          | 0/511 [00:00<?, ?it/s]

INFO:simpletransformers.classification.classification_utils: Saving features into cached file cache_dir/cached_train_bert_128_4_2
/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:310: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,

Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Running Epoch 0 of 1:   0%|          | 0/64 [00:00<?, ?it/s]

INFO:simpletransformers.classification.classification_model: Training of bert model complete. Saved to outputs/.
INFO:simpletransformers.classification.classification_utils: Converting to features started. Cache is not used.

  0%|          | 0/511 [00:00<?, ?it/s]

INFO:simpletransformers.classification.classification_utils: Saving features into cached file cache_dir/cached_dev_bert_128_4_2

Running Evaluation:   0%|          | 0/64 [00:00<?, ?it/s]

INFO:simpletransformers.classification.classification_model:{'mcc': 0.6336686704055358, 'eval_loss': 0.5712130414322019}

In [17]:
print(result)

for entry in wrong_predictions:
  print(entry)

{'mcc': 0.6336686704055358, 'eval_loss': 0.5712130414322019}
{'guid': 13, 'text_a': '退職代行を利用するのはあり?なし?利用する際の注意点も解説!\n\n\n\n\n\n\n\n', 'text_b': None, 'label': 2}
{'guid': 24, 'text_a': '先のことを考えて今やらなければいけないこと/できることをやる。\n誰も予測できないワクワクする体験や成長を追求していきます。\n \n', 'text_b': None, 'label': 2}
{'guid': 25, 'text_a': '多くの人はProgateを勧めているけど、\n僕は効率が悪いと思う。\n\n昔は僕もProgateを楽しんでやっていたが、、、\n………\n\n\n\n', 'text_b': None, 'label': 0}
{'guid': 39, 'text_a': 'おはようございます!\n\n・Instagram投稿作成\n・スクール生のオンラインレッスン\n・プログラミング教材作成\n\n今日も今日とて\u200d\n1週間のスタートダッシュを朝活でブーストかけましょう!\n\n\n\n\n', 'text_b': None, 'label': 2}
{'guid': 43, 'text_a': '今日も早起きPrと読書\n\nPrはマルチカメラとLumetriカラーでの色補正。色補正を書籍の通りにやってますが、実際に自分でアレンジして決めるのは、難易度高すぎ\n\n読書は「バビロンの大富豪の教え」読了\n明日からはまた別の本(マンガ)\n\nLove&amp;Peaceよろしく\n\n\n\n\n', 'text_b': None, 'label': 1}
{'guid': 48, 'text_a': '未経験からのプログラミングあるある、その5\n\nプログラミングスクールに通う\n\nスクールの良し悪しではなく、お金を払って満足してしまうことが問題。\n私もプログラミング書籍を購入して満足し、よく積読してる\nまずはProgateなどで基礎知識をつけてから検討することをオススメ!\n\n', 'text_b': None, 'label': 3}
{'guid': 55, 'text_a': "I've completed HTMLCSS Study2.\nBut I don't know if it's enough or not…\n \n\n\nProgateの学習は、独学で足りない部分をスクールでどうフォローしてもらえるか体験する!\u200d\n\n://t.co/MZ3VuOVeXg", 'text_b': None, 'label': 1}
{'guid': 58, 'text_a': 'プログラミング学習で課金するのは月千円のProgateで充分\nあとは公式ドキュメントを読めば大丈夫\n公式ドキュメントを読んでも理解できない人は向いてないから違う仕事探した方がいいよ\n\n高いスクール、情報商材は金の無駄\n\n', 'text_b': None, 'label': 3}
{'guid': 61, 'text_a': 'エンジニアに資格は?\n\nなりたい人は必要\n見えないものを扱う業界で\n目に見えてわかりやすい\n自信がつく\n\nなってる人は不要\nそもそも、そんなこと何も気にしてないから\n\n  ', 'text_b': None, 'label': 2}
{'guid': 62, 'text_a': 'エンジニア=webアプリ\nのイメージかもしれませんが\n\n街中で見るモノのほとんどは\n機械制御されていて\nそれを開発してるエンジニアがいます\n\n選択肢は色々あるよという話です\n\n  ', 'text_b': None, 'label': 2}
{'guid': 64, 'text_a': 'プログラミング初心者\u200d「3時間プログラミング勉強したら疲れてこれ以上出来ない、どうしたら良い?」\n\nぴっかちゃん「PCメガネを買おう因みに運営者はブルーライトカット50%のPCメガネを毎日つけてるよ」\n\n\n\n\n', 'text_b': None, 'label': 2}
{'guid': 65, 'text_a': 'こんばんワークマン\u200d今日は妻が︎休みなので、チャンズの夕ご飯はお任せです但し達をお風呂に入れる時はバスタオル持って待機になります。自分達の夕ご飯は簡単に済ませます\n\n\n\n://t.co/IEqvdaNCDw', 'text_b': None, 'label': 2}
{'guid': 66, 'text_a': '\n\nMicrosoft産のJavascript亜種\nJavascript変換して実行\n関連書籍や資料等の情報は少なめ\n\nJavascriptの上位互換\nというと各所から怒られそう\n\n  ', 'text_b': None, 'label': 2}
{'guid': 67, 'text_a': '特にエンジニアって教え方下手くそな人が多すぎる\nコミュニケーション能力も分からない知識を分かる様に教えるのが生業の営業能力もマジないんだからさ\n\n  ', 'text_b': None, 'label': 2}
{'guid': 69, 'text_a': '絶対(absolute)と相対(relative)の違い、プログラミングに限らず、Excelを使ったりPCで作業するときでも重要です。たとえば家の場所を伝えるとき、住所を教えるのが絶対指定、○○の3軒右隣の向かいだよって教えるのが相対指定。\n ', 'text_b': None, 'label': 2}
{'guid': 72, 'text_a': 'こんにちワーゲンバスいつもの釣り場でお昼まで頑張りましたが、ボラとフグ祭りで終わってしまいました。\nやはり、私以外の餌が入って無いからだと思います。チヌも寄って居るのに私が釣り切れて居ないのだと思います\n\n\n \n://t.co/FQqT9kAyJv', 'text_b': None, 'label': 2}
{'guid': 74, 'text_a': 'おはようございます!\n本日も朝活1時間程度やりました\nこれから家族と買い物とか公園とか行って、子供が昼寝したタイミングで再開します\n休日は家族優先です\n\n \n\n\n\n\n', 'text_b': None, 'label': 2}
{'guid': 75, 'text_a': '学生さんやフリーランスの方でプログラミング頑張っている方と繋がりたいです!どなたでも大歓迎です!\n\n自分と繋がったらすごいメリットがあるかもです。\n\n\n\n \n\n\n', 'text_b': None, 'label': 2}
{'guid': 76, 'text_a': '学生さんやフリーランスの方でプログラミング頑張っている方と繋がりたいです!どなたでも大歓迎です!\n\n自分と繋がったらすごいメリットがあるかもです。\n\n\n\n \n\n\n', 'text_b': None, 'label': 2}
{'guid': 90, 'text_a': 'gemファイルは非公式で作成された便利ツールのようなもの、という認識ですが、\n・どこでgemファイルの存在を知るの?\n・どこで使い方(含まれるメソッドなど)を知るの?\nと、謎はあります。\n\n「Ruby on Rails5学習レッスンXI」レッスンを修了しました!  ', 'text_b': None, 'label': 3}
{'guid': 95, 'text_a': '「JavaScript」\nで人気があるツイートです!(最新50件中)\n\n[いいね:7]\nJav…\n\n\n[いいね:9]\n「JavaScript学習レッスンIII」コ…\n\n\n[いいね:22]\nTwitterのITエンジニア「IT業界人…\n', 'text_b': None, 'label': 2}
{'guid': 100, 'text_a': '結局のところ、"やり続ける"ことが重要。\n習慣にするまでが大変だけど、現場に出てから習慣をつける方がもっと大変。\n人生のどこかで頑張る時期を作ってもいいのでは?\n \n', 'text_b': None, 'label': 2}
{'guid': 101, 'text_a': '-勉強会メリット-\n❶切磋琢磨できる仲間がいる\n❷同じ目標を持った同志がいる\n❸情報収集\n❹アウトプットで知識の定着\n❺自信がついて楽しい\n❻悩みが解決するから継続できる\n \n', 'text_b': None, 'label': 2}
{'guid': 103, 'text_a': 'スポーツにせよ、ビジネスにせよ、できる人というのは、オンとオフの切り替えが実にはっきりしていますよね。そんな人・チームになりたいですね。\n \n', 'text_b': None, 'label': 2}
{'guid': 115, 'text_a': '先のことを考えて今やらなければいけないこと/できることをやる。\n誰も予測できないワクワクする体験や成長を追求していきます。\n \n', 'text_b': None, 'label': 2}
{'guid': 116, 'text_a': '100日後くらいに個人開発するぞ!day031    ', 'text_b': None, 'label': 1}
{'guid': 117, 'text_a': '100日後くらいに個人開発するぞ!day031     ', 'text_b': None, 'label': 1}
{'guid': 131, 'text_a': 'プログラミングスクールに通う前にみんなぐぐると思うんだけど、結局どの記事を信じたらいいのかって言う事に悩み出すんよね。\n\n  \n', 'text_b': None, 'label': 2}
{'guid': 149, 'text_a': 'Progateをやった後に、もっとPythonについて詳しく知りたい、という場合は。問題数がとても多いので、自身の課題解決に必要な最低限の部分だけやって、実務に移るのが良いでしょう。\n', 'text_b': None, 'label': 1}
{'guid': 159, 'text_a': '先のことを考えて今やらなければいけないこと/できることをやる。\n誰も予測できないワクワクする体験や成長を追求していきます。\n \n', 'text_b': None, 'label': 2}
{'guid': 165, 'text_a': 'テックエキスパートを受講して\n失敗したと思うこと\n\n完全未経験で挑んだこと\n事前学習をサボったこと\n無料相談を後まわしにしたこと\n\n今の自分なら事前にProgateをやります\nあとは早めに無料相談を受けます\n', 'text_b': None, 'label': 3}
{'guid': 172, 'text_a': '多くの人はProgateを勧めているけど、僕は効率が悪いと思う。昔は僕もProgateを楽しんでやっていたが、、、…………', 'text_b': None, 'label': 0}
{'guid': 173, 'text_a': '多くの人はProgateを勧めているけど、僕は効率が悪いと思う。昔は僕もProgateを楽しんでやっていたが、、、…………', 'text_b': None, 'label': 0}
{'guid': 176, 'text_a': ' \n\n', 'text_b': None, 'label': 2}
{'guid': 178, 'text_a': '多くの人はProgateを勧めているけど、\n僕は効率が悪いと思う。\n\n昔は僕もProgateを楽しんでやっていたが、、、\n………\n\n\n\n', 'text_b': None, 'label': 0}
{'guid': 183, 'text_a': 'ブログはこちら!!!\n \n\n\n\n\n\n\n\n\n\n\n', 'text_b': None, 'label': 2}
{'guid': 187, 'text_a': 'Progateで特になにも作りたいものはないと気付いてしまった', 'text_b': None, 'label': 0}
{'guid': 191, 'text_a': '100日後くらいに個人開発するぞ!day042    ', 'text_b': None, 'label': 2}
{'guid': 194, 'text_a': 'Pick Up Ticket \n\nProgate無料版by \n\n://t.co/KC8vyU1t7J', 'text_b': None, 'label': 2}
{'guid': 212, 'text_a': 'その職業訓練校の先生はとても頭がいい方なようで\n\n  ://t.co/40uS6qqMpC', 'text_b': None, 'label': 2}
{'guid': 214, 'text_a': 'エンジニアは稼げる? Progate代表が答える切り抜き  ', 'text_b': None, 'label': 2}
{'guid': 215, 'text_a': '求人はこちら!\n\n \n\n\n\n\n\n', 'text_b': None, 'label': 2}
{'guid': 220, 'text_a': 'Python入門書籍の紹介です。練習問題が豊富でおすすめです。\n \n', 'text_b': None, 'label': 3}
{'guid': 225, 'text_a': 'まともな大人向けUIがあるならそっちに慣れた人は使い続けてもらって\nインタラクティブに学習できるUIを作るべきなのかも、\n例えばprogateみたいなのを、業務システムでも簡単にできる開発環境があればなあ', 'text_b': None, 'label': 2}
{'guid': 237, 'text_a': '会社員が身につけたいITスキルは「プログラミング」「データ分析」「動画作成」Progate調べ via ', 'text_b': None, 'label': 2}
{'guid': 238, 'text_a': 'Progateをどれだけやったところで仕事ができる域にはならない…\n\n今日Progate何周すれば案件取れる的なの聞いてる人見てそう思った', 'text_b': None, 'label': 0}
{'guid': 239, 'text_a': 'ヘイ社でのProgate for Businessの利用事例出てた\n', 'text_b': None, 'label': 3}
{'guid': 240, 'text_a': '5/31にSchooさん、Progateさんと一緒にイベントを開催します!\n是非ご参加くださいー\n', 'text_b': None, 'label': 2}
{'guid': 242, 'text_a': '退職代行を利用するのはあり?なし?利用する際の注意点も解説!\n\n\n\n\n\n\n\n\n', 'text_b': None, 'label': 2}
{'guid': 243, 'text_a': 'rails5 progate整理メモpassword_digest   ', 'text_b': None, 'label': 2}
{'guid': 247, 'text_a': '100日後くらいに個人開発するぞ!day035     ', 'text_b': None, 'label': 2}
{'guid': 248, 'text_a': 'まずはprogate・ドットインストールからプログラミングに挑戦してみてはいかがでしょうか??\n\n\n\n', 'text_b': None, 'label': 3}
{'guid': 252, 'text_a': '経験3年とはいえProgateで躓くレベルの人に自信もってとか言われてもねー', 'text_b': None, 'label': 2}
{'guid': 275, 'text_a': '広告のご出稿をいただける企業様や団体様を「1社様限定」で募集しています。\n\n\n\n\n\n\n\n\n', 'text_b': None, 'label': 2}
{'guid': 281, 'text_a': 'おはようございます!\n本日、追加募集の最終締め切り日ですー!\n\n次回は9月開講予定ですので、\n「それまで待ってられない!」\nって方は早めにご応募ください!\n\n\n\n\n://t.co/gxpELLM0nQ', 'text_b': None, 'label': 1}
{'guid': 283, 'text_a': '広告のご出稿をいただける企業様や団体様を「1社様限定」で募集しています。\n\n\n\n\n\n\n\n\n', 'text_b': None, 'label': 2}
{'guid': 288, 'text_a': '伴走する大人にとってもとっつきやすい\n 。無料コンテンツありますが、ある程度やるには月額料金かかりまさこれを英語版でやってみるのは面白い気がする。\n \n\n', 'text_b': None, 'label': 3}
{'guid': 293, 'text_a': ' 。\n道場レッスン含め、Ⅴまでコンプリートしとくと基礎としては十分かなと思いました。半日あればコンプリートできます\n', 'text_b': None, 'label': 3}
{'guid': 299, 'text_a': 'Pythonの練習問題をお探しの方に安くておすすめ!!実践式はじめてのPython問題集まとめ.ver3\n \n', 'text_b': None, 'label': 3}
{'guid': 303, 'text_a': 'Day23\nprogate終了\n\n\nProgateで「Web開発コース(Ruby on Rails)」を修了しました!  ', 'text_b': None, 'label': 2}
{'guid': 304, 'text_a': '100日後くらいに個人開発するぞ!day047    ', 'text_b': None, 'label': 2}
{'guid': 305, 'text_a': '100日後くらいに個人開発するぞ!day047    ', 'text_b': None, 'label': 2}
{'guid': 306, 'text_a': '\n記事タイトル:curlコマンドをPythonプログラムに変換する手順\n\n 詳しくはこちら\n \n\n \n \n ', 'text_b': None, 'label': 3}
{'guid': 307, 'text_a': '\n記事タイトル:Linuxでコマンドを同時実行(並列実行)する手順\n\n 詳しくはこちら\n \n\n \n \n ', 'text_b': None, 'label': 3}
{'guid': 313, 'text_a': '日付:6月16日\n勉強内容:第3回講座、Progate、バナートレース一個、購入本でのPhotoshop練習\n時間:7時間\n\n\n ', 'text_b': None, 'label': 1}
{'guid': 316, 'text_a': '日付:6月16日\n勉強内容:progate、Photoshopを触る、第3回授業の予習\nボケすぎて明日授業って忘れかけてた、、がんばろ!\n\n', 'text_b': None, 'label': 1}
{'guid': 324, 'text_a': '\n寝る前にスライドをみよう。\n\nタイトル:トランザクションスクリプトは何がダメなのか?\n\n 詳しくはこちら\n \n\n \n ', 'text_b': None, 'label': 3}
{'guid': 325, 'text_a': '\n新卒採用の動向変化とは?\n内定者の時期にどんなフォローをすると良いのか?\n\n人事責任者の経歴を持つCOOの宮林へのインタビュー記事をお届けします\n\n「Progate COOが語る、就活生の意識の変化」\n', 'text_b': None, 'label': 3}
{'guid': 330, 'text_a': 'ポテパンキャンプの評判・口コミは?就職先が100%Web系開発企業?\n\n\n\n\n\n\n\n\n', 'text_b': None, 'label': 3}
{'guid': 336, 'text_a': '今まで見てきたプログラミングスクール記事の中で一番いい。\n\n \n', 'text_b': None, 'label': 3}
{'guid': 337, 'text_a': 'プログラミングスクールに通う前にみんなぐぐると思うんだけど、結局どの記事を信じたらいいのかって言う事に悩み出すんよね。\n\n  \n', 'text_b': None, 'label': 3}
{'guid': 340, 'text_a': '\n記事タイトル:curlコマンドをPythonプログラムに変換する手順\n\n 詳しくはこちら\n \n\n \n \n ', 'text_b': None, 'label': 3}
{'guid': 341, 'text_a': '\n以下の記事を隙間時間で閲覧してみよう。\n\n記事タイトル:フロントエンドid属性管理戦略\n\n 詳しくはこちら\n \n\n \n ', 'text_b': None, 'label': 3}
{'guid': 346, 'text_a': 'SUNABACOにWebデザイン系の書籍がありますのでProgateがある程度進んだら実践してみるのも良いですよ! ', 'text_b': None, 'label': 3}
{'guid': 349, 'text_a': 'レバテックカレッジの評判・口コミは?大学生/大学院生ならコスパ最強?\n\n\n\n\n\n\n\n\n', 'text_b': None, 'label': 3}
{'guid': 353, 'text_a': 'うちのCOOの記事。遠くにはやく行きたいのです。本当に。\nあと、にんじゃわんこが相変わらずかわいい。\n\n  ', 'text_b': None, 'label': 3}
{'guid': 356, 'text_a': '\n一息の際に下記記事をみよう。\n\nタイトル:わかりやすいシステム構成図の書き方\n\n 詳しくはこちら\n \n\n \n ', 'text_b': None, 'label': 3}
{'guid': 357, 'text_a': 'JavaScript忘備録  ', 'text_b': None, 'label': 2}
{'guid': 362, 'text_a': 'pythonを無料で学習できるサイト\n\n〇Progate→基礎文法学習\n〇→基礎文法学習&amp;問題演習\n〇→模写コーティング\n', 'text_b': None, 'label': 1}
{'guid': 367, 'text_a': '\n記事タイトル:curlコマンドをPythonプログラムに変換する手順\n\n 詳しくはこちら\n \n\n \n \n ', 'text_b': None, 'label': 3}
{'guid': 368, 'text_a': '\n記事タイトル:nasneを無線接続する手順\n\n 詳しくはこちら\n \n\n \n \n ', 'text_b': None, 'label': 3}
{'guid': 377, 'text_a': '現役のエンジニアが受講した評判/スキルによるオススメ度 \n\n\n\n \n\n', 'text_b': None, 'label': 3}
{'guid': 379, 'text_a': '\n一息の際に下記記事をみよう。\n\nタイトル:6歳娘「パパ、型による条件分岐はできないの?」\n\n 詳しくはこちら\n \n\n \n ', 'text_b': None, 'label': 2}
{'guid': 381, 'text_a': 'スクールやWebカリキュラムだけだとどうしても受け入れハードルあがるんだけど、プロダクション(本番環境)レベルの開発経験があるエンジニアが増えたら、企業側の採用・受け入れの幅も広がりそうだなー\n  ', 'text_b': None, 'label': 3}
{'guid': 383, 'text_a': '\n記事タイトル:SQLite3でUPSERTを実現する2つの方法\n\n 詳しくはこちら\n \n\n \n \n ', 'text_b': None, 'label': 3}
{'guid': 384, 'text_a': '\n記事タイトル:Linuxでコマンドを同時実行(並列実行)する手順\n\n 詳しくはこちら\n \n\n \n \n ', 'text_b': None, 'label': 3}
{'guid': 385, 'text_a': 'Pythonを激安で学べるStart Labの内容・評判・口コミのまとめ\n\n\n\n\n\n\n\n\n', 'text_b': None, 'label': 3}
{'guid': 387, 'text_a': '今まで見てきたプログラミングスクール記事の中で一番笑った\n\n \n', 'text_b': None, 'label': 3}
{'guid': 391, 'text_a': '日付:6月4日\n勉強内容:Progate初級編・バナートレース作成・課題取組み\nやっぱり週末は勉強時間取るの難しいな\n\n', 'text_b': None, 'label': 2}
{'guid': 395, 'text_a': '今日はあまり勉強できなかった分、明日がんばる…!\n\n日付:6月4日\n勉強内容: progate(HTML&amp;CSS初級編)\n時間:1時間\n\n ', 'text_b': None, 'label': 2}
{'guid': 401, 'text_a': 'こんにちワーゲンバス\nビノブリューも紹介して良かったのでは?私は好きなんですが\n\n\n \n://t.co/BXVc9SXFka', 'text_b': None, 'label': 2}
{'guid': 408, 'text_a': 'そして山浦さんの独学エンジニアはだいぶおすすめです。月額1000円ぐらいであそこまで学べる動画教材って中々ないです\nProgateやるよりは実践的なことを学べると思います。\n://t.co/xKIoYZJpIf', 'text_b': None, 'label': 0}
{'guid': 409, 'text_a': 'お疲れ様です\n\n6月7日\n課題のバナー作成\n読書「バナーデザインのきほん」\n\n本読むのも楽しい\n明日はprogate頑張ろ\n\n\n\n\n ', 'text_b': None, 'label': 2}
{'guid': 432, 'text_a': 'こんにちワーゲンバス若い頃デパートで一目惚れしたホックニーの帆船の絵を30万円で本気で買いそうになった事を思い出す。買わなかった事を今でも悔んでます\n\n\n \n://t.co/tyMjuH7xzP', 'text_b': None, 'label': 2}
{'guid': 433, 'text_a': '私の"Progateの次に学ぶ!Python演習問題100問パック!データ型・制御構文編"コース修了証書 ', 'text_b': None, 'label': 1}
{'guid': 436, 'text_a': '先のことを考えて今やらなければいけないこと/できることをやる。\n誰も予測できないワクワクする体験や成長を追求していきます。\n \n', 'text_b': None, 'label': 2}
{'guid': 450, 'text_a': '<Javascript Ⅳクラスについて> \n●クラスはオブ...『progate』2時間 ', 'text_b': None, 'label': 1}
{'guid': 451, 'text_a': '製薬企業研究者や薬学部生のための\n\n', 'text_b': None, 'label': 3}
{'guid': 453, 'text_a': 'Youtubeでもgiveコンテンツ発信し続けていてスゴイ\n\n\n://t.co/VPgUgMfccs', 'text_b': None, 'label': 1}
{'guid': 455, 'text_a': '求人はコチラ!!!\n \n\n\n\n\n\n', 'text_b': None, 'label': 1}
{'guid': 468, 'text_a': '次のステップは学習したことを復習しつつ、本で理解を深めようと思います。\n\n使う本は『1冊ですべて身につくHTML&amp;CSSとWebデザイン入門』です。\n\nアドバイス等頂けたら嬉しいです。\n\n\n', 'text_b': None, 'label': 2}
{'guid': 470, 'text_a': '5/31 HTML&amp;CSSの勉強開始\n\nProgateでHTML&amp;CSSの初級編と中級編をやりました。\n\n初級編で大体の枠組みやレイアウトのイメージはつかんだが、中級編は難しくこんな物があるのか程度の理解\n\n\n', 'text_b': None, 'label': 0}
{'guid': 471, 'text_a': '3日目\n\n『1冊ですべて身につくHTML&amp;CSSとWebデザイン入門』のchapter3までを読みました。\n\nProgateで学習したことは本当に基礎の基礎なんだなあと実感。\n\n\n', 'text_b': None, 'label': 0}
{'guid': 472, 'text_a': '学習初めてかれこれ2ヶ月経ちますが、まだHTML&amp;CSSで苦戦中。Progate有料版申し込んだのに、他の学習をストップして模写ばかりしてるからもったいないかな気分転換に、先にJavaScriptとかやるべきか・・・。\n\n\n \n', 'text_b': None, 'label': 0}
{'guid': 473, 'text_a': '道場レッスンでつまづいてからしばらくやってなかったらめっちゃ忘れてるからその先進めても理解に時間がかかった。負のループはいってるわ...\n\n  ', 'text_b': None, 'label': 0}
{'guid': 475, 'text_a': 'とりあえずProgateのロードマップにしたがってこれ読んでるけど、ほとんど理解できてない\n\n\n\n\n\n://t.co/sYFztWlGE8', 'text_b': None, 'label': 0}
{'guid': 477, 'text_a': '物事の捉え方\n\n例えば「飲み会」\nネガティブめんどくさい。時間の浪費\nポジティブ人から学びにしよう!!\n\n生きていると外的要因がたくさん\nすべてポジティブ転換できたら生きやすい世の中\n流石に全ては無理かな…\n\n\n\n', 'text_b': None, 'label': 2}
{'guid': 478, 'text_a': ' 30年以上前は、コマンドプロンプトやターミナル自体がOSだったので、シンプルに「パソコンを使える=コマンドが使える」だったんですよ\n\nMS-DOSの略が答えられたら、あなたは確実に初老です。\n\n\n\n \n', 'text_b': None, 'label': 2}
{'guid': 507, 'text_a': '\n自分が中級者か初級者かも、わからない。\nProgateとかドットインストールとか、、、独学でいろいろ学べるサービスあるけど、一部有料、、、\nだから、自分ができていない、穴を探すためにも、完全無料のサービスを教えてほしい、(親とは不仲ww)', 'text_b': None, 'label': 2}
{'guid': 510, 'text_a': '本業でITエンジニアの人材採用マーケティングをやってますが、ターゲットの理解がまだ全然足りていないと痛感。エンジニアが利用する情報サイトに登録したり、Progateに登録してプログラミングの勉強も始めました。普段考えていることなど、本質も理解したい。\n\n', 'text_b': None, 'label': 3}

In [19]:
predictions, raw_outputs = model.predict(test['text'].values.tolist())
prediction = pd.read_csv(FILENAME).query('labels != labels').drop('labels',axis=1)
prediction['prediction'] = pd.Series(predictions)

INFO:simpletransformers.classification.classification_utils: Converting to features started. Cache is not used.

  0%|          | 0/2330 [00:00<?, ?it/s]

  0%|          | 0/292 [00:00<?, ?it/s]

In [20]:
prediction.head()

                                                  text  prediction
398  テックジム(techgym)の評判・口コミは？就職サポートはある？��\n\nhttps:/...         3.0
399  よいしょYoutube〜〜う！��✨\nJava Ⅱ 学習編：12.配列上書いちゃう？��✨...         3.0
400  あくまでも個人的な意見だけど\nprogateを周回してからテキストに入った方が復習にもなる...         3.0
401  テックギークの評判・口コミは？Shopifyエンジニアは今が狙い目？��\n\nhttps:...         3.0
402       ついにジャズピアノもprogate式に… https://t.co/xe9aGdnbHS         3.0

In [21]:
from google.colab import files
filename = 'predictions.csv'
prediction.to_csv(filename, encoding='utf-8-sig')
files.download(filename)